--建立資料庫
USE [master]
GO

/****** Object:  Database [CompanyDB]    Script Date: 2024/10/25 下午 05:33:47 ******/
CREATE DATABASE [CompanyDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CompanyDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CompanyDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CompanyDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CompanyDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CompanyDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CompanyDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CompanyDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CompanyDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CompanyDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CompanyDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CompanyDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CompanyDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CompanyDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CompanyDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CompanyDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CompanyDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CompanyDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CompanyDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CompanyDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CompanyDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CompanyDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CompanyDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CompanyDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CompanyDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CompanyDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CompanyDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CompanyDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CompanyDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CompanyDB] SET  MULTI_USER 
GO

ALTER DATABASE [CompanyDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CompanyDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CompanyDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CompanyDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CompanyDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CompanyDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CompanyDB] SET  READ_WRITE 
GO





--建立Company 資料表
CREATE TABLE CompanyData (
TableDate DATE,
DataYearMonth VARCHAR(10),
CompanyCode INT PRIMARY KEY,
CompanyName VARCHAR(50),
Industry VARCHAR(20),
MonthlyRevenue DECIMAL(18, 2),
PreviousMonthRevenue DECIMAL(18, 2),
LastYearMonthlyRevenue DECIMAL(18, 2),
MonthOnMonthGrowth DECIMAL(5, 2),
YearOnYearGrowth DECIMAL(5, 2),
CumulativeMonthlyRevenue DECIMAL(18, 2),
LastYearCumulativeRevenue DECIMAL(18, 2),
YearToDateGrowth DECIMAL(5, 2),
Remarks VARCHAR(100)
);